version: "3.5"

services:
  tcr-nginx:
    image: nginx
    hostname: tcr-nginx
    container_name: tcr-nginx
    volumes:
      - ../nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/conf.d:/etc/nginx/conf.d
      - ../nginx/log:/var/log/nginx
      - ../app/public:/etc/nginx/public
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    networks:
      - twitch-chat-raffle-network
    depends_on:
      - tcr-app

  tcr-app:
    image: tcr-app
    hostname: tcr-app
    container_name: tcr-app    
    ports:
      - "3000:3000"
    environment:
      - MONGO_HOST=tcr-mongodb
      - MONGO_PORT=28018
    networks:
      - twitch-chat-raffle-network
    depends_on:
      - tcr-mongodb

  tcr-crawler:
    image: tcr-crawler
    hostname: tcr-crawler
    container_name: tcr-crawler
    volumes:
      - ../crawler/logs:/crawler/logs
    ports:
      - "8000:8000"
    environment:
      - MONGO_HOST=tcr-mongodb
      - MONGO_PORT=28018      
    networks:
      - twitch-chat-raffle-network    

  tcr-mongodb:
    image: mongo
    hostname: tcr-mongodb
    container_name: tcr-mongodb
    ports:
      - "28018:28018"
    volumes:
      - ../mongodb/data:/data/db
      - ../mongodb/cnf:/etc/mongo
      - ../mongodb/log:/var/log/mongodb
    entrypoint: ["mongod", "-f", "/etc/mongo/mongod.conf"]
    environment:
      TZ: Asia/Seoul
      # MONGO_INITDB_ROOT_USERNAME: "twitch_crawler_raffle"
      # MONGO_INITDB_ROOT_PASSWORD: "twitch_crawler_raffle123!"
      # MONGO_INITDB_DATABASE: "twitch_raffle"
    networks:
      - twitch-chat-raffle-network
    restart: always

networks:
  twitch-chat-raffle-network:
    driver: bridge